# Appendix

(ref:tbl-cor-cap) Correlations between CBM-R Predictors (CORE and Traditional) and Continuous Outcomes (Spring CBM Comprehension and SBAC ELA/L) by Grade.

```{r tbl-cor, results="asis"}

cor_comp <- data_comp %>% 
  select(grade_core, wcpm_core.wave1_r, wcpm_easycbmcore.wave1_r, wcpm_core.wave4_r, wcpm_easycbmcore.wave4_r, readingcomp_easycbm.spring) %>% 
  group_by(grade_core) %>% 
  summarize(core_fall = cor(wcpm_core.wave1_r, readingcomp_easycbm.spring, use = "pairwise.complete.obs"),
            trad_fall = cor(wcpm_easycbmcore.wave1_r, readingcomp_easycbm.spring, use = "pairwise.complete.obs"),
            core_spring = cor(wcpm_core.wave4_r, readingcomp_easycbm.spring, use = "pairwise.complete.obs"),
            trad_spring = cor(wcpm_easycbmcore.wave4_r, readingcomp_easycbm.spring, use = "pairwise.complete.obs")
  ) %>% 
  mutate(measure = "CBM Comprehension")
            
cor_sbac <- data_sbac %>% 
  select(grade_core, wcpm_core.wave1_r, wcpm_easycbmcore.wave1_r, wcpm_core.wave4_r, wcpm_easycbmcore.wave4_r, sbac_score) %>% 
  group_by(grade_core) %>%  
  summarize(
    core_fall = cor(wcpm_core.wave1_r, sbac_score, use = "pairwise.complete.obs"),
    trad_fall = cor(wcpm_easycbmcore.wave1_r, sbac_score, use = "pairwise.complete.obs"),
    core_spring = cor(wcpm_core.wave4_r, sbac_score, use = "pairwise.complete.obs"),
    trad_spring = cor(wcpm_easycbmcore.wave4_r, sbac_score, use = "pairwise.complete.obs")
    ) %>% 
  mutate(measure = "SBAC ELA/L Score")

cor_info <- cor_comp %>% 
  bind_rows(cor_sbac) %>% 
  mutate(across(c(core_fall:trad_spring), ~str_sub(sprintf("%.2f", round(., 2)), 2)))

variable_labels(cor_info$core_fall) <- "CORE"
variable_labels(cor_info$trad_fall) <- "Traditional"
variable_labels(cor_info$core_spring) <- "CORE"
variable_labels(cor_info$trad_spring) <- "Traditional"

cor_info <- cor_info %>%
  rename(Grade = grade_core) %>% 
  mutate(Grade = paste0("Grade ", Grade)) %>% 
  group_by(measure) %>% 
  nest()

apa_table(
  list(
    `CBM Comprehension` = cor_info$data[[1]],
    `SBAC ELA/L Score` = cor_info$data[[2]]
    ), 
  caption = "(ref:tbl-cor-cap)", 
  col_spanners = list(`Distal (Fall)` = c(2, 3), `Proximal (Spring)` = c(4, 5)),
  align = c("l", rep("r", 4)),
  escape = FALSE
  ) 

```

(ref:tbl-asr-ex-cap) Example Passage Scored by the ASR.

```{r tbl-asr-ex, results='asis'}
tbl_asr_ex <- read_csv(here::here("data", "tbl_asr_ex.csv")) %>% 
  rowid_to_column("Word")

tbl_asr_ex <- tbl_asr_ex %>% 
  slice(1:25) %>% 
  bind_cols(
    slice(tbl_asr_ex, 26:49) %>% 
      add_row()
  ) %>% 
  as.data.frame(.)

variable_labels(tbl_asr_ex$Word...1) <- "Word"
variable_labels(tbl_asr_ex$ref...2) <- "Ref"
variable_labels(tbl_asr_ex$start...3) <- "Start"
variable_labels(tbl_asr_ex$end...4) <- "End"
variable_labels(tbl_asr_ex$hyp...5) <- "Hyp"
variable_labels(tbl_asr_ex$score...6) <- "Score"
variable_labels(tbl_asr_ex$Word...7) <- "Word"
variable_labels(tbl_asr_ex$ref...8) <- "Ref"
variable_labels(tbl_asr_ex$start...9) <- "Start"
variable_labels(tbl_asr_ex$end...10) <- "End"
variable_labels(tbl_asr_ex$hyp...11) <- "Hyp"
variable_labels(tbl_asr_ex$score...12) <- "Score"

apa_table(
  tbl_asr_ex, 
  caption = "(ref:tbl-asr-ex-cap)", 
  align = c(rep("r", 12)),
  longtable = TRUE,
  escape = FALSE,
  note = "Word = word number. Ref = Reference word from the passage. Start = centiseconds from when the passage was displayed on the sreen to when the student started reading the reference word. End = centiseconds from when the passage was displayed on the sreen to when the student ended reading the reference word. Hyp = hypthosized word recorded by the ASR. Score = ASR word score (0 = incorrect, 1 = correct). ** = words omitted as recorded by the ASR."
  )
```


(ref:tbl-lgms-results-cap) Latent Growth Model Parameter Estimates by Grade.

```{r tbl-lgms-results, results='asis'}

lgms_info <- lgms %>% 
  mutate(paramtable = map(params, paramtable_fx)) %>% 
  select(Grade = grade_core, measure, paramtable) %>% 
  arrange(Grade, measure) %>% 
  pivot_wider(
    names_from = measure,
    values_from = paramtable
  ) %>% 
  unnest() %>% 
  select(-param_names1) %>% 
  mutate(across(c(parameter1:z1), ~ifelse(Grade == 4, "", .)),
         across(c(parameter:z1), ~ifelse(. == "", "--", .)),
         Grade = paste0("Grade ", Grade)) %>% 
  rename(`Parameter Names` = param_names,
         Parameter = parameter) %>% 
  as.data.frame(.)

variable_labels(lgms_info$se) <- "\\emph{SE}"
variable_labels(lgms_info$z) <- "\\emph{z}-value"
variable_labels(lgms_info$parameter1) <- "Parameter"
variable_labels(lgms_info$se1) <- "\\emph{SE}"
variable_labels(lgms_info$z1) <- "\\emph{z}-value"

lgms_info <- lgms_info %>% 
  group_by(Grade) %>% 
  nest()

apa_table(
  list(
    `Grade 2` = lgms_info$data[[1]],
    `Grade 3` = lgms_info$data[[2]],
    `Grade 4` = lgms_info$data[[3]]
    ), 
  col_spanners = list(`CORE` = c(2, 4), `Traditional` = c(5, 7)),
  caption = "(ref:tbl-lgms-results-cap)", 
  align = c("l", rep("r", 6)),
  longtable = TRUE,
  escape = FALSE
  )
```
